### PR TITLE
Use script_run_time to get the correct time zone

### PR DESCRIPTION
**Pull request by pbchase**
It's tine thing, but the case interview dates are being set in UTC. This change will move them to UTC

### CODE REVIEW

**Comment by ChemiKyle** [comment]
I'm not ignoring this, but each time I've tested `nrow(new_lab_results) == 0`, this review about time needs good timing.

**Comment by pbchase** [comment]
> I'm not ignoring this, but each time I've tested `nrow(new_lab_results) == 0`, this review about time needs good timing.

Perhaps it's "time" to merge it.

**Comment by ChemiKyle** [comment]
Perhaps it should have been! There's a merge conflict now that github has declared "[...] too complex to resolve in the web editor". Your new target is:

https://github.com/ctsit/tt_engine/blob/bb0f7489aed82987e3aec4595035906977e00f5e/R/data_creating.R#L233

**Comment by pbchase** [comment]
@ChemiKyle, please make a PR that replaces these in appropriate uses of `now()` in the library code with a uses of `script_run_time`.  i.e., fix these lines:

```
→ pwd
/Users/pbc/git/tt_engine/r
(10:50:35) ± [pbc@Philips-MacBook-Pro.local] ~/git/tt_engine/r (develop ✗) 
→ grep -r "now()" *
data_creating.R:               case_report_datetime = format(now(), "%Y-%m-%d %H:%M"),
data_writing.R:  if (email_subject == "") email_subject <- paste( Sys.getenv("EMAIL_SUBJECT"), with_tz( now(), tzone = Sys.getenv("TIME_ZONE") ) )
```

Then close this PR.

**Comment by ChemiKyle** [comment]
New PR made at #123, closing this PR.

**Pull request closed without merging**
