### PR TITLE
Get positive cases from new lab results

### PR DESCRIPTION
**Pull request by ljwoodley**
Uncomment test portions to create fake data. Also, should there be empty UF id in prod cases db? We may miss possible retest as there's no uf id to match on.

Addresses issue #68

### CODE REVIEW

**Comment by pbchase** [comment]
> Uncomment test portions to create fake data. Also, should there be empty UF id in prod cases db? We may miss possible retest as there's no uf id to match on.

We only get test results from UF people. If we can't match them to a known UFID we will not load the data.

**Comment by pbchase** [comment]
@ljwoodley, I want to loop @ChemiKyle in to test this. I tried to test it but got jammed up on the creation of new cases. That said, the insertion of retest records worked well.

As to features, I want this function to move one additional thing from the new results to Cases: negative retests. Perhaps the name `get_positive_cases_from_new_lab_results` was a bad name. maybe `get_new_lab_results_for_cases` would be better. Feel free to rename it.

To review, this function needs to return three types of records:

1. New positives
1. Positive retests for existing cases
1. Negative retests for existing cases

Adding the 3rd component might be as simple as changing this line in `get_positive_cases_from_new_lab_results`

```
positive_cases <- new_lab_results %>%
    filter(results == 1)
```

to something more like this

```
  read_case_data <- get_case_records()

  case_ufids <- read_case_data %>%
    filter(!is.na(case_emp_ufid)) %>%
    select(case_emp_ufid) %>%
    mutate(case_emp_ufid = as.character(case_emp_ufid))
  
  positive_cases <- new_lab_results %>%
    filter(results == 1 | ufid %in% case_ufids$case_emp_ufid)
```

**Comment by pbchase** [comment]
this code is better

```
  read_case_data <- get_case_records()

  case_ufids <- read_case_data %>%
    filter(!is.na(case_emp_ufid)) %>%
    select(case_emp_ufid) %>%
    mutate(case_emp_ufid = as.character(case_emp_ufid))

  positive_cases <- new_lab_results %>%
    filter(results == 1) %>%
    filter(uf_id_from_epic %in% case_ufids$case_emp_ufid)
```

but i think `uf_id_from_epic` might be wrong.  please check that this is the best UFID.  I want the one we made from the coalesce.

**Comment by ljwoodley** [comment]
uf_id is the one created in the coalesce https://github.com/ctsit/tt_engine/blob/9350658f98fa7fe36343acbabd16b5d7ee28d985/functions.R#L197

**Comment by ljwoodley** [comment]
hold review. I need to get demographic data from `all_rows_in_redcap_results`. This is visible on when `redcap_repeat_instance == 1`

**Comment by ljwoodley** [comment]
Ready fo review.

**Pull request merged**
