### PR TITLE
Set delivery preference

### PR DESCRIPTION
**Pull request by ljwoodley**
Addresses issue #115

### CODE REVIEW

**Comment by ljwoodley** [comment]
Hold on this. I need to put in sanity checks and output email if error occurs.

**Comment by ljwoodley** [comment]
@pbchase  I'll need to run this on Monday morning to see the output of `query_output <- dbSendStatement(con, sql)`  if that's ok with you? I don't really understand what's qualified as a success from the documentation.

**Comment by pbchase** [comment]
I love what you wrote.  I also agree with your concern about definitions of success. I'll offer a couple examples that might answer your questions. In testing the PR, your code ran the query successfully and got this output:

```
>   query_output <- dbSendStatement(con, sql)
> typeof(query_output)
[1] "S4"
> query_output
<MariaDBResult>
  SQL  
  update redcap_surveys_participants
  set delivery_preference = 'SMS_INVITE_WEB'
  where participant_id in
    (
      select participant_id from
      (
        SELECT
          rcsp.participant_id as participant_id
        FROM
          redcap_surveys_participants rcsp
          inner join redcap_surveys rcs on (rcsp.survey_id = rcs.survey_id)
          inner join redcap_surveys_response rcsr on (rcsp.participant_id = rcsr.participant_id)
          left join redcap_data phone on (phone.record = rcsr.record and phone.project_id = rcs.project_id)
          left join redcap_data email on (email.record = rcsr.record and email.project_id = rcs.project_id)
        where
          rcs.project_id = 26 and
          phone.field_name = 'contact_method_prefer_sms' and
          email.field_name = 'contact_method_prefer_email' and
          phone.value is not null and
          rcsp.delivery_preference is null
      ) as dummy
    )
  
  ROWS Fetched: 0 [complete]
       Changed: 0
```

This is not surprising as a I ran the query last night at 6:30 and there seems to have been no contact tracing work done on the positives that came in late last night. A non-zero "Changed" count would more common, but both zero and non-zero are valid.

I precipitate an error, I intentionally broke the SQL and got this result:

```
> rm(query_output)
>   query_output <- dbSendStatement(con, sql)
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.participant_id as participant_id
        FROM
          redcap_surveys_particip' at line 9 [1064]
> typeof(query_output)
Error in typeof(query_output) : object 'query_output' not found
```

I think you'll need to wrap the query in a tryCatch to deal with bad SQL. I expect we will slowly evolve it as we learn more about REDCap's normal behavior here.

As to successful queries, let's do this:

1. For the subject, go with something like 

```
email_subject <- paste("Delivery preference set for Contact SX checks", "|", Sys.getenv("INSTANCE"), "|", script_run_time)
```

2. For the body, go with something like 

```
paste("Delivery preference set for", NN, "contact records. This is the output of the query:\n\n", query_output)
```

**Comment by ljwoodley** [comment]
This is ready for review. @ChemiKyle

**Comment by pbchase** [comment]
This looks good.

**Comment by ljwoodley** [comment]
dbExecute appears to be the more efficient call.

Screen Shot 2020-07-13 at 10 17 37 AM


Screen Shot 2020-07-13 at 10 18 57 AM

**Pull request merged**
